### ISSUE TITLE
[FEATURE] Supporters Page Design #546

### ISSUE THREAD

**Issue by dansousamelo** [FGA-GCES/houdini#1]
**Original Issue**
https://github.com/houdiniproject/houdini/issues/536
Based on issue 536 where a design improvement is proposed on the support part.

**Screenshots**
![image](https://user-images.githubusercontent.com/48137972/128788270-c7317517-b0f5-49eb-8fcc-5a6bf5ff7e1a.png)
Atual page.

**Describe the solution you'd like**
With the help of UI/UX concepts we suggest a complete rethink, producing a high-fidelity prototype as a goal.

**Additional context**
A style guide will also be proposed.

**Comment by dansousamelo** [comment]
We are done, the result can be seen below
![issueGCES](https://user-images.githubusercontent.com/48137972/129074535-8da967db-d885-4a80-b725-13445125f285.gif)

**Comment by lucasgandac** [comment]
O protótipo de alta-fidelidade pode ser visualizado completamente através do link https://www.figma.com/file/TOfZ6ee6YwYQsWeqWiX3BS/Untitled?node-id=0%3A1

**Comment by dansousamelo** [comment]
Issue completa,foi uma tarefa árdua visto que o processo de design é iterativo, e em formato de ciclo como podemos ver abaixo.

![image](https://user-images.githubusercontent.com/48137972/134570762-4754a382-2d15-4f07-93bf-57a0f8640747.png)

**Comment by dansousamelo** [comment]
Todos os protótipos elaborados foram colocados na issue original, conversamos com toda a equipe do Houdini anotando e implementando _feedbacks_ dos mesmos. O resultado final ficou:
![image](https://user-images.githubusercontent.com/48137972/134571121-84598ec0-d3c1-4afc-9d2b-8262711b5c96.png)

**Comment by dansousamelo** [comment]
Aqui estão os componentes do material design elaborados para auxiliar nessa issue:
https://www.figma.com/file/VLp94zT7eXdDSKLdGgNGFL/Material-Design-Components?node-id=0%3A1
