### ISSUE TITLE
[BUG] The nonprofit creation allows you to create it with a state that is not in the US

### ISSUE THREAD

**Issue by igor-paiva** [FGA-GCES/houdini#4]
## Original issue

[The nonprofit creation allows you to create it with a state that is not in the US (#586)](https://github.com/houdiniproject/houdini/issues/586)

## Problem

This problem is happening because the create a nonprofit script allows the creation in states that are not in the US.

## Solution

A validation was added to the nonprofit model.

## Other changes

- The gem [countries](https://rubygems.org/gems/countries/versions/1.2.5?locale=en-US) was used to get the available states
- The state code constraints was also changed to use the gem [countries](https://rubygems.org/gems/countries/versions/1.2.5?locale=en-US)

**Comment by thiagolopess** [comment]
Merged!
